### PR TITLE
Add `pyproject.toml` and format files

### PR DESCRIPTION
**Pull request by kunaltyagi**

### CODE REVIEW

**Comment by kunaltyagi** [comment]
@mosherubin PTAL

**Comment by Farigh** [comment]
Great idea to add a Linter.

I would advise putting a new step in the actions to enforce those.

Also, you changed the `%` syntaxe for the `.format(...)` approach.
I would suggest migrating to python [f-strings](https://peps.python.org/pep-0498/) instead.

**Comment by kunaltyagi** [comment]
Everything so far has been automatic via black and ruff, so I'm gonna rely on them instead of manually using the f strings

No linter is tested yet. It'll take work to enable that on the CI

**Comment by kunaltyagi** [comment]
@Farigh Could you try using the instructions in README and let me know if you can get the hatch setup working?

**Comment by Farigh** [comment]
Sorry, I'm nowhere near a python dev env ATM.
Maybe later this week

**Pull request merged**
