### PR TITLE
Add more C++ and Objective-C/C++ file extensions

### PR DESCRIPTION
**Pull request by smokris**

### CODE REVIEW

**Comment by kunaltyagi** [comment]
@smokris Before I merge this, do you want to add tests to reflect the changes?

**Comment by smokris** [comment]
> Before I merge this, do you want to add tests to reflect the changes?

I see that there are unit tests embedded in each rule… but this is a change to `nsiqcppstyle_exe`'s `main` function.  Could you elaborate on how you'd like to structure a test for that?

Alternatively, since this is a small and low-risk change, a test might not be necessary.

**Comment by kunaltyagi** [comment]
The tests also check if the behavior is valid wrt the file extension. Eg: run in header files, and not in c files. See ```RULE_5_3_A_provide_doxygen_function_comment_on_function_in_header.py``` for reference

**Comment by kunaltyagi** [comment]
@smokris Any updates?

**Comment by smokris** [comment]
Sorry I didn't get back to you earlier.  Thanks for adding the tests and merging this!

**Comment by kunaltyagi** [comment]
You're welcome. It wasn't a big undertaking. Hope your experience is good with nsiqcppstyle 😄

**Pull request merged**
